POST http://localhost:3001/api/users/signup
Content-Type: application/json

{
  "name": "Amfdsdfsd",
  "email": "dsami@admin.com",
  "password": "Amin21s13",
  "jobRole": "HR Worker"
}

###
# @name login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "dsami@admin.com",
  "password": "Amin21s13"
}

###
GET http://localhost:3001/api/tracks/{{uid}}
Authorization: BEARER {{authToken}}
###
GET http://localhost:3001/api/tasks/11
Authorization: BEARER {{authToken}}
###

@authToken = {{login.response.body.token}}
@uid = {{login.response.body.id}}