-- MySQL Script generated by MySQL Workbench
-- Sun Nov  5 17:42:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnboardingToolDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnboardingToolDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnboardingToolDB` DEFAULT CHARACTER SET utf8 ;
USE `OnboardingToolDB` ;

-- -----------------------------------------------------
-- Table `OnboardingToolDB`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnboardingToolDB`.`tasks` (
  `id` INT NOT NULL,
  `name` VARCHAR(85) NOT NULL,
  `description` VARCHAR(5000) NULL,
  `is_done` TINYINT NOT NULL DEFAULT 0,
  `tracks_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tracks_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_tasks_tracks1_idx` (`tracks_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_tracks1`
    FOREIGN KEY (`tracks_id`)
    REFERENCES `OnboardingToolDB`.`tracks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnboardingToolDB`.`tracks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnboardingToolDB`.`tracks` (
  `id` INT NOT NULL,
  `name` VARCHAR(85) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnboardingToolDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnboardingToolDB`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnboardingToolDB`.`users_has_tracks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnboardingToolDB`.`users_has_tracks` (
  `users_id` VARCHAR(36) NOT NULL,
  `tracks_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `tracks_id`),
  INDEX `fk_users_has_tracks_tracks1_idx` (`tracks_id` ASC) VISIBLE,
  INDEX `fk_users_has_tracks_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_tracks_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `OnboardingToolDB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_tracks_tracks1`
    FOREIGN KEY (`tracks_id`)
    REFERENCES `OnboardingToolDB`.`tracks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `OnboardingToolDB`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `OnboardingToolDB`;
INSERT INTO `OnboardingToolDB`.`users` (`id`, `name`, `email`, `password`, `created`, `last_login`) VALUES ('fsd7f6dfg-..345,dfg7fg6asdj543nds843', 'Admin', 'admin@admin.com', 'admin', DEFAULT, DEFAULT);

COMMIT;

